port: 4000
host: 0.0.0.0
safe: false

# Site settings
title: Still Followers for Instagram
description: The answer to life, the universe and everything, or not. It is just a portfolio with some of the best iOS apps of the month, the year and all times. Enjoy!
keywords: angel, subirana, fernandez, bobgoo, apps, ios, iphone, ipad, safe, web, still, friends, facebook, kids, spot, indie, development, design, free, apps
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

url: https://igers.bobgoo.com
enforce_ssl: igers.bobgoo.com

# App Setting
app_title: Still Followers
app_subtitle: for Instagram
app_description: Have you ever wondered how to get more followers on Instagram?
appstore_link: "https://itunes.apple.com/app/apple-store/id1394497522?pt=674507&ct=web&mt=8"

# User settings
username: Angel Subirana
email: support@bobgoo.com
twitter_username: stillfollowers
instagram_username: stillfollowers

# Google-analytics
google_analytics_key: UA-25289053-4

# Opengraph
opengraph:
    title: 
    description:
    image: /assets/img/FBBanner.png
    height: 630
    width: 1200

# Favicons
favicon:     /assets/favicon/favicon.ico
touch_icon:  /assets/faviconapple-touch-icon.png

exclude: ['package.json', 'src' , 'node_modules']
