port: 4000
host: 0.0.0.0
safe: false

# Site settings
title: Still Followers for Instagram
description: "Have you ever wondered how to grow on Instagram? Let Still Followers do the hard work...  Get powerful tracking and analytics of your Instagram followers. Give up wasting your time... KEEP IT SHORT AND SIMPLE: Analytics well done!"
keywords: still, followers, instagram, twitter, facebook, friends, angel, subirana, fernandez, bobgoo, labs, apps, ios, iphone, ipad, follow, unfollow, unfollower, who, blocked, me, viewed, my, mass, tag, stalker, profile, spy, bulk, fan, ghost, iger, manager, track, tracking, community, account, copy, grow, like, stat, audit, post, insight, get, more, inactive, cm
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

url: https://igers.bobgoo.com
enforce_ssl: igers.bobgoo.com

# App Setting
app_title: Still Followers
app_subtitle: for Instagram
app_description: Have you ever wondered how to get more followers on Instagram?
appstore_link: "https://itunes.apple.com/app/apple-store/id1394497522?pt=674507&ct=web&mt=8"

# User settings
username: Angel Subirana
email_username: support@bobgoo.com
twitter_username: stillfollowers
instagram_username: stillfollowers

# Google-analytics
google_analytics_key: UA-25289053-4

# Opengraph
opengraph:
    title: 
    description:
    image: /assets/img/FBBanner.png
    height: 630
    width: 1200

# Favicons
favicon:     /assets/favicon/favicon.ico
touch_icon:  /assets/faviconapple-touch-icon.png

exclude: ['package.json', 'src' , 'node_modules']
